#! /bin/sh

set -x
sudo cp /home/pi/install/mjpg-streamer/mjpg_streamer /usr/local/bin
sudo cp /home/pi/install/mjpg-streamer/output_http.so /usr/local/lib
sudo cp /home/pi/install/mjpg-streamer/input_file.so /usr/local/lib
sudo cp -r /home/pi/install/mjpg-streamer/www /usr/local/www





