#! /bin/sh
# Install script for RaspiBrick

echo ------ Running RaspiBrick installation. Version 1.7 - March 26, 2017

if [ "$1" = "update" ]
  then
     echo "Update requested"
  else
     echo "Normal installation"
fi  


# Display commands
set -x

sudo rm -rf /home/pi/raspibrick
sudo rm -rf /home/pi/programs
sudo rm -rf /home/pi/scripts
sudo rm -rf /home/pi/mygeany
sudo rm -rf /home/pi/rpi-tutorial

echo ------ Creating directories ------ 
mkdir /home/pi/raspibrick
mkdir /home/pi/raspibrick/jars
mkdir /home/pi/raspibrick/lib
mkdir /home/pi/raspibrick/res
mkdir /home/pi/programs
mkdir /home/pi/scripts
mkdir /home/pi/mygeany
mkdir /home/pi/mygeany/gpanel
mkdir /home/pi/rpi-tutorial

if [ "$1" != "update" ]
  then
    echo ------ Installing Bluetooth software ------ 
    sudo apt-get install bluetooth
    sudo apt-get install bluez-tools
    sudo apt-get install python-bluez    
    sudo sdptool add SP

    echo ------ Installing sox software ------ 
    sudo apt-get install sox
    sudo apt-get install libsox-fmt-mp3 

    echo ------ Installing python-dev ------ 
    sudo apt-get install python-dev

    echo ------ Installing pyqt4 software ------ 
    sudo apt-get install python-qt4

    echo ------ Installing sqlite software ------ 
    sudo apt-get install sqlite3

    echo ------ Installing sqlitebrowser software ------ 
    sudo apt-get install sqlitebrowser

fi

echo ------ Copying files ------ 
sudo cp /home/pi/install/modules /etc/modules
sudo cp /home/pi/install/bashrc-root /root/.bashrc
sudo cp /home/pi/install/bashrc-pi /home/pi/.bashrc
sudo cp /home/pi/install/sudoers /etc
sudo cp /home/pi/install/logo/raspibrick.png /usr/share/pixel-wallpaper

# for camera support:
sudo cp /home/pi/install/mjpg-streamer/mjpg_streamer /usr/local/bin
sudo cp /home/pi/install/mjpg-streamer/output_http.so /usr/local/lib
sudo cp /home/pi/install/mjpg-streamer/input_file.so /usr/local/lib
sudo cp -r /home/pi/install/mjpg-streamer/www /usr/local/www

chmod +x /home/pi/install/jrun
sudo cp /home/pi/install/jrun /usr/bin

chmod +x /home/pi/install/jrun.sh
cp /home/pi/install/jrun.sh /home/pi/raspibrick

chmod +x /home/pi/install/startApp
sudo cp /home/pi/install/startApp /usr/bin
cp /home/pi/install/KillIdleProc.py /home/pi/raspibrick

chmod +x /home/pi/install/pyrun
sudo cp -f /home/pi/install/pyrun /usr/bin

chmod +x /home/pi/install/rmon
sudo cp /home/pi/install/rmon /usr/bin

# Disable screen blanking in LXDE with directly connected screen
sudo mv /etc/lightdm/lightdm.conf /etc/lightdm/lightdm.conf.origin
sudo cp /home/pi/install/lightdm.conf /etc/lightdm

chmod +x /home/pi/install/update-raspibrick
sudo cp /home/pi/install/update-raspibrick /usr/bin

chmod +x /home/pi/install/rkill
sudo cp /home/pi/install/rkill /usr/bin

chmod +x /home/pi/install/RaspiBrickStart
sudo cp /home/pi/install/RaspiBrickStart /etc/init.d

chmod +x /home/pi/install/autostart.sh
cp /home/pi/install/autostart.sh /home/pi/raspibrick

chmod +x /home/pi/install/rename-host
cp /home/pi/install/rename-host /home/pi/raspibrick

cp -r /home/pi/install/programs/* /home/pi/programs
cp -r /home/pi/install/scripts/* /home/pi/scripts
cp /home/pi/install/jars/* /home/pi/raspibrick/jars
cp /home/pi/install/lib/* /home/pi/raspibrick/lib
cp /home/pi/install/res/* /home/pi/raspibrick/res
cp /home/pi/install/*.py /home/pi/raspibrick
cp /home/pi/install/Fonts/*.* /home/pi/Fonts
cp /home/pi/install/Pictures/*.* /home/pi/Pictures
cp -R /home/pi/install/Music/*.* /home/pi/Music
cp /home/pi/install/rpi-tutorial/*.* /home/pi/rpi-tutorial
cp /home/pi/install/mygeany/*.* /home/pi/mygeany
cp /home/pi/install/mygeany/gpanel/*.* /home/pi/mygeany/gpanel

echo ------ Installing autostart ------ 
sudo update-rc.d RaspiBrickStart defaults

echo ------ Mounting FAT partition ------ 
sudo mkdir /mnt/recovery
sudo mount /dev/mmcblk0p1 /mnt/recovery

echo ------ Copying RaspiBrickConfig.jar ------ 
chmod +x /home/pi/install/RaspiBrickConfig.jar
sudo cp /home/pi/install/RaspiBrickConfig.jar  /mnt/recovery/RaspiBrickConfig.jar

echo ------ Copying wpa_supplicant.conf ------ 
sudo cp /etc/wpa_supplicant/wpa_supplicant.conf  /mnt/recovery/wpa_supplicant.conf
